POST http://localhost:3000/playlists/67177d46-c78a-42ea-bb9e-f1f6f1f97f5a/add
Accept: application/json
Content-Type: application/json
Authorization: User admin

{
  "songIds": [
    "03637ff1-03f6-4d2b-97ea-f814e94ddcf9"
  ]
}

###
