PUT http://localhost:3000/playlists/622090bf-f663-42ce-b052-ed92eafc75dd
Accept: application/json
Content-Type: application/json
Authorization: User admin

{
  "name": "My Playlist (Updated)",
  "description": "My updated playlist"
}

###
