PUT http://localhost:3000/playlists/67fc8f7d-95ab-43e1-8131-c27ba73f4e42
Accept: application/json
Content-Type: application/json
Authorization: User admin

{
  "name": "My Playlist (Updated)",
  "description": "My updated playlist"
}

###
